#!/usr/bin/env python3
"""Extract reflection data from markdown files and generate a single HTML app with Apple-style design."""

import os
import re
import json
from datetime import datetime, timezone
from pathlib import Path


def to_miniprogram_entry(entry):
    """Convert internal reflection entry to miniprogram/API schema (camelCase)."""
    return {
        'date': entry['date'],
        'summary': entry.get('summary') or '',
        'tags': entry.get('tags') or [],
        'content': entry.get('daily_content') or entry.get('content') or '',
        'hasReflection': bool(entry.get('has_reflection')),
        'reflectionSummary': entry.get('reflection_summary') or '',
        'reflectionTags': entry.get('reflection_tags') or [],
        'reflectionContent': entry.get('reflection_content') or '',
    }


def export_data_files(workspace, reflections):
    """
    Export:
      1) reflections.json  — remote source for miniprogram (wx.request)
      2) miniprogram/data/reflections.js — offline fallback packaged with the app
    """
    mp_list = [to_miniprogram_entry(r) for r in reflections]
    payload = {
        'updatedAt': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
        'count': len(mp_list),
        'reflections': mp_list,
    }

    json_path = workspace / 'reflections.json'
    json_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding='utf-8',
    )
    print(f"Generated {json_path} ({len(mp_list)} entries)")

    mp_dir = workspace / 'miniprogram' / 'data'
    mp_dir.mkdir(parents=True, exist_ok=True)
    js_path = mp_dir / 'reflections.js'
    # Keep array shape so offline require() matches historical usage
    js_body = (
        '// Auto-generated by build_reflection_app.py — do not edit by hand\n'
        '// Offline fallback. Online data is fetched from config.dataUrl.\n'
        'module.exports = '
        + json.dumps(mp_list, ensure_ascii=False, indent=2)
        + ';\n'
    )
    js_path.write_text(js_body, encoding='utf-8')
    print(f"Generated {js_path}")

    return payload

def extract_date_from_filename(filename):
    """Extract date from filename like '2026-7-1-每日反思.md'"""
    match = re.match(r'(\d{4})-(\d{1,2})-(\d{1,2})-每日反思', filename)
    if match:
        year, month, day = match.groups()
        return f"{year}-{int(month):02d}-{int(day):02d}"
    return None

def extract_title(content):
    """Extract the main title from the content."""
    for line in content.split('\n'):
        if line.startswith('# �'):
            return line.replace('# 🪞', '').strip()
    return None

def extract_summary(content):
    """Extract a short summary from the content."""
    lines = content.split('\n')
    in_summary = False
    summary_lines = []
    for line in lines:
        if '## 💡 一句话总结' in line:
            in_summary = True
            continue
        if in_summary:
            if line.startswith('## ') or line.startswith('---'):
                break
            if line.strip():
                summary_lines.append(line.strip())
    
    if summary_lines:
        text = ' '.join(summary_lines)
        return text[:200] + ('...' if len(text) > 200 else '')
    
    # Fallback: use first meaningful content
    for line in lines:
        if line.startswith('## 🪞') or line.startswith('## �'):
            continue
        if line.startswith('> ') and len(line) > 20:
            return line[2:].strip()[:150] + '...'
    
    return None

def extract_tags(content):
    """Extract key tags/themes from content."""
    tags = []
    tag_patterns = [
        r'薄弱点\s*\d*[：:]\s*(.+?)(?:\n|$)',
        r'###\s*(.+?)(?:\n|$)',
    ]
    for pattern in tag_patterns:
        matches = re.findall(pattern, content)
        for m in matches[:2]:
            clean = m.strip().replace('**', '')[:30]
            if clean and clean not in tags:
                tags.append(clean)
    return tags[:3]

def extract_reflection_summary(content):
    """Extract summary from reflection.md format files."""
    lines = content.split('\n')
    # Look for key sections
    summary_lines = []
    in_event = False
    for line in lines:
        if line.startswith('## 事件') or line.startswith('## 目标与结果'):
            in_event = True
            continue
        if in_event:
            if line.startswith('## ') or line.startswith('---'):
                break
            if line.strip() and not line.startswith('- ') and not line.startswith('#'):
                summary_lines.append(line.strip())
                if len(summary_lines) >= 2:
                    break
    
    if summary_lines:
        return ' '.join(summary_lines)[:200]
    
    # Fallback: first meaningful line
    for line in lines:
        if line.strip() and not line.startswith('#') and not line.startswith('-') and len(line) > 10:
            return line.strip()[:150]
    return '反思记录'

def extract_reflection_tags(content):
    """Extract tags from reflection.md content."""
    tags = []
    tag_patterns = [
        r'薄弱点\s*\d*[：:]\s*(.+?)(?:\n|$)',
        r'###\s*(.+?)(?:\n|$)',
    ]
    for pattern in tag_patterns:
        matches = re.findall(pattern, content)
        for m in matches[:2]:
            clean = m.strip().replace('**', '')[:30]
            if clean and clean not in tags:
                tags.append(clean)
    return tags[:3]


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Build reflections.json/html from markdown")
    parser.add_argument(
        '--workspace',
        default=None,
        help='md 所在目录，默认为脚本所在目录；云端 workflow 用 --workspace 指向拉取目录',
    )
    args = parser.parse_args()
    workspace = Path(args.workspace).resolve() if args.workspace else Path(__file__).resolve().parent
    
    # Find all reflection files (both types)
    reflections = []
    
    # First pass: find all daily reflection files (每日反思)
    daily_files = {}
    for f in sorted(workspace.glob('*-每日反思*.md')):
        date_str = extract_date_from_filename(f.name)
        if date_str:
            content = f.read_text(encoding='utf-8')
            title = extract_title(content)
            summary = extract_summary(content)
            tags = extract_tags(content)
            daily_files[date_str] = {
                'date': date_str,
                'filename': f.name,
                'title': title,
                'summary': summary,
                'tags': tags,
                'content': content,
                'type': 'daily'
            }
    
    # Second pass: find all reflection files (reflection.md)
    reflection_files = {}
    for f in sorted(workspace.glob('*-reflection.md')):
        # Extract date from filename like '2026-07-22-reflection.md' or '2026-7-23-reflection.md'
        match = re.match(r'(\d{4})-(\d{1,2})-(\d{1,2})-reflection', f.name)
        if match:
            year, month, day = match.groups()
            date_str = f"{year}-{int(month):02d}-{int(day):02d}"
            content = f.read_text(encoding='utf-8')
            reflection_files[date_str] = {
                'date': date_str,
                'filename': f.name,
                'title': f'反思记录',
                'summary': extract_reflection_summary(content),
                'tags': extract_reflection_tags(content),
                'content': content,
                'type': 'reflection'
            }
    
    # Merge: get all unique dates
    all_dates = sorted(set(list(daily_files.keys()) + list(reflection_files.keys())))
    
    for date_str in all_dates:
        daily = daily_files.get(date_str)
        refl = reflection_files.get(date_str)
        
        # Create merged entry
        entry = {
            'date': date_str,
            'type': 'merged'
        }
        
        if daily:
            entry['title'] = daily['title']
            entry['summary'] = daily['summary']
            entry['tags'] = daily['tags']
            entry['content'] = daily['content']
            entry['daily_content'] = daily['content']
        else:
            entry['title'] = ''
            entry['summary'] = ''
            entry['tags'] = []
            entry['content'] = ''
            entry['daily_content'] = ''
        
        if refl:
            entry['reflection_title'] = refl['title']
            entry['reflection_summary'] = refl['summary']
            entry['reflection_tags'] = refl['tags']
            entry['reflection_content'] = refl['content']
            # If no daily file, use reflection as primary
            if not daily:
                entry['title'] = refl['title']
                entry['summary'] = refl['summary']
                entry['tags'] = refl['tags']
                entry['content'] = refl['content']
        else:
            entry['reflection_title'] = ''
            entry['reflection_summary'] = ''
            entry['reflection_tags'] = []
            entry['reflection_content'] = ''
        
        entry['has_reflection'] = refl is not None
        reflections.append(entry)
    
    # Sort by date
    reflections.sort(key=lambda x: x['date'])
    
    print(f"Found {len(reflections)} reflection files")

    # Export JSON + miniprogram offline fallback (for remote dynamic updates)
    export_data_files(workspace, reflections)
    
    # Generate HTML
    data_json = json.dumps(reflections, ensure_ascii=False, indent=2)
    
    html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, viewport-fit=cover">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<title>每日反思 | Daily Reflection</title>
<style>
:root {{
  --bg-primary: #f2f2f7;
  --bg-secondary: #ffffff;
  --bg-tertiary: #f9f9fb;
  --bg-elevated: rgba(255,255,255,0.92);
  --text-primary: #1c1c1e;
  --text-secondary: #3c3c43;
  --text-tertiary: #8e8e93;
  --accent: #007aff;
  --accent-soft: rgba(0,122,255,0.12);
  --accent-hover: #0066d6;
  --separator: rgba(60,60,67,0.12);
  --shadow-sm: 0 1px 3px rgba(0,0,0,0.04);
  --shadow: 0 2px 12px rgba(0,0,0,0.06);
  --shadow-lg: 0 8px 40px rgba(0,0,0,0.1);
  --shadow-xl: 0 16px 56px rgba(0,0,0,0.12);
  --radius-lg: 20px;
  --radius: 14px;
  --radius-sm: 10px;
  --radius-xs: 8px;
  --font: -apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', 'Helvetica Neue', 'PingFang SC', sans-serif;
  --font-mono: 'SF Mono', 'Fira Code', 'Cascadia Code', monospace;
  --transition: 0.3s cubic-bezier(0.32, 0.72, 0, 1);
  --transition-fast: 0.15s cubic-bezier(0.32, 0.72, 0, 1);
}}

@media (prefers-color-scheme: dark) {{
  :root {{
    --bg-primary: #000000;
    --bg-secondary: #1c1c1e;
    --bg-tertiary: #2c2c2e;
    --bg-elevated: rgba(28,28,30,0.92);
    --text-primary: #ffffff;
    --text-secondary: #ebf5ff;
    --text-tertiary: #8e8e93;
    --accent: #0a84ff;
    --accent-soft: rgba(10,132,255,0.18);
    --accent-hover: #409cff;
    --separator: rgba(84,84,88,0.36);
    --shadow-sm: 0 1px 3px rgba(0,0,0,0.2);
    --shadow: 0 2px 12px rgba(0,0,0,0.3);
    --shadow-lg: 0 8px 40px rgba(0,0,0,0.4);
    --shadow-xl: 0 16px 56px rgba(0,0,0,0.5);
  }}
}}

* {{ margin: 0; padding: 0; box-sizing: border-box; }}

body {{
  font-family: var(--font);
  background: var(--bg-primary);
  color: var(--text-primary);
  min-height: 100vh;
  min-height: 100dvh;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  overflow-x: hidden;
  letter-spacing: -0.01em;
}}

/* === HEADER === */
.header {{
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 100;
  background: var(--bg-elevated);
  backdrop-filter: saturate(180%) blur(24px);
  -webkit-backdrop-filter: saturate(180%) blur(24px);
  border-bottom: 0.5px solid var(--separator);
  padding: env(safe-area-inset-top, 0) 0 0;
}}

.header-inner {{
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 20px;
  max-width: 680px;
  margin: 0 auto;
}}

.header-btn {{
  width: 36px;
  height: 36px;
  border-radius: 50%;
  border: none;
  background: var(--bg-tertiary);
  color: var(--accent);
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: var(--transition-fast);
  -webkit-tap-highlight-color: transparent;
}}

.header-btn:hover {{
  background: var(--accent-soft);
  transform: scale(1.05);
}}

.header-btn:active {{
  transform: scale(0.92);
}}

.header-btn:disabled {{
  opacity: 0.3;
  pointer-events: none;
}}

.header-center {{
  flex: 1;
  text-align: center;
  cursor: pointer;
  -webkit-tap-highlight-color: transparent;
  padding: 8px 12px;
  border-radius: 8px;
  transition: background 0.15s;
  position: relative;
  z-index: 1;
}}

.header-center:hover {{
  background: var(--accent-soft);
}}

.header-center:active {{
  background: rgba(0,122,255,0.2);
}}

.header-center h1 {{
  font-size: 17px;
  font-weight: 600;
  letter-spacing: -0.3px;
  color: var(--text-primary);
}}

.header-center .subtitle {{
  font-size: 11px;
  font-weight: 500;
  color: var(--text-tertiary);
  margin-top: 1px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}}

/* === MAIN CONTENT === */
.content {{
  max-width: 680px;
  margin: 0 auto;
  padding: calc(80px + env(safe-area-inset-top, 0)) 20px calc(100px + env(safe-area-inset-bottom, 0));
}}

/* === DATE HERO === */
.date-hero {{
  text-align: center;
  padding: 24px 0 32px;
  animation: fadeInUp 0.5s var(--transition);
}}

@keyframes fadeInUp {{
  from {{ opacity: 0; transform: translateY(12px); }}
  to {{ opacity: 1; transform: translateY(0); }}
}}

@keyframes fadeIn {{
  from {{ opacity: 0; }}
  to {{ opacity: 1; }}
}}

.date-hero .day-number {{
  font-size: 72px;
  font-weight: 700;
  letter-spacing: -3px;
  line-height: 0.9;
  background: linear-gradient(135deg, var(--text-primary) 0%, var(--accent) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  margin-bottom: 4px;
}}

.date-hero .date-info {{
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  margin-top: 8px;
}}

.date-hero .month-year {{
  font-size: 14px;
  font-weight: 600;
  color: var(--text-tertiary);
  text-transform: uppercase;
  letter-spacing: 1.2px;
}}

.date-hero .weekday {{
  font-size: 14px;
  font-weight: 600;
  color: var(--accent);
  background: var(--accent-soft);
  padding: 3px 10px;
  border-radius: 20px;
}}

/* === CARDS === */
.card {{
  background: var(--bg-secondary);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-sm);
  overflow: hidden;
  margin-bottom: 16px;
  animation: fadeInUp 0.4s var(--transition);
  transition: transform 0.2s, box-shadow 0.2s;
}}

.card:hover {{
  box-shadow: var(--shadow);
}}

.card-header {{
  padding: 18px 22px;
  border-bottom: 0.5px solid var(--separator);
  display: flex;
  align-items: center;
  justify-content: space-between;
}}

.card-header h2 {{
  font-size: 17px;
  font-weight: 600;
  display: flex;
  align-items: center;
  gap: 8px;
  letter-spacing: -0.2px;
}}

.card-header .badge {{
  font-size: 11px;
  font-weight: 600;
  color: var(--accent);
  background: var(--accent-soft);
  padding: 3px 8px;
  border-radius: 12px;
}}

.card-body {{
  padding: 20px 22px;
  font-size: 15px;
  line-height: 1.7;
  color: var(--text-secondary);
}}

.card-body p {{
  margin-bottom: 14px;
}}

.card-body p:last-child {{
  margin-bottom: 0;
}}

/* === REFLECTION CONTENT === */
.reflection-content {{
  font-size: 15px;
  line-height: 1.75;
}}

.reflection-content h1 {{
  font-size: 22px;
  font-weight: 700;
  margin-bottom: 16px;
  letter-spacing: -0.3px;
  color: var(--text-primary);
}}

.reflection-content h2 {{
  font-size: 17px;
  font-weight: 600;
  margin: 24px 0 12px;
  color: var(--text-primary);
  letter-spacing: -0.2px;
  padding-bottom: 8px;
  border-bottom: 0.5px solid var(--separator);
}}

.reflection-content h3 {{
  font-size: 15px;
  font-weight: 600;
  margin: 16px 0 8px;
  color: var(--text-primary);
}}

.reflection-content blockquote {{
  border-left: 3px solid var(--accent);
  padding: 10px 16px;
  margin: 14px 0;
  background: var(--accent-soft);
  border-radius: 0 var(--radius-sm) var(--radius-sm) 0;
  font-size: 14px;
  color: var(--text-secondary);
}}

.reflection-content blockquote p {{
  margin-bottom: 0;
}}

.reflection-content table {{
  width: 100%;
  border-collapse: separate;
  border-spacing: 0;
  margin: 14px 0;
  font-size: 13px;
  border-radius: var(--radius-sm);
  overflow: hidden;
  border: 0.5px solid var(--separator);
}}

.reflection-content th {{
  background: var(--bg-tertiary);
  font-weight: 600;
  text-align: left;
  padding: 10px 12px;
  color: var(--text-secondary);
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 0.3px;
}}

.reflection-content td {{
  padding: 10px 12px;
  border-top: 0.5px solid var(--separator);
}}

.reflection-content tr:nth-child(even) td {{
  background: rgba(0,0,0,0.02);
}}

@media (prefers-color-scheme: dark) {{
  .reflection-content tr:nth-child(even) td {{
    background: rgba(255,255,255,0.02);
  }}
}}

.reflection-content ul, .reflection-content ol {{
  padding-left: 22px;
  margin: 10px 0;
}}

.reflection-content li {{
  margin-bottom: 6px;
  font-size: 14px;
  line-height: 1.6;
}}

.reflection-content code {{
  font-family: var(--font-mono);
  font-size: 13px;
  background: var(--bg-tertiary);
  padding: 2px 6px;
  border-radius: 4px;
  border: 0.5px solid var(--separator);
}}

.reflection-content pre {{
  background: var(--bg-tertiary);
  border: 0.5px solid var(--separator);
  padding: 16px;
  border-radius: var(--radius-sm);
  overflow-x: auto;
  margin: 14px 0;
  font-size: 13px;
}}

.reflection-content pre code {{
  background: transparent;
  padding: 0;
  border: none;
  color: inherit;
}}

.reflection-content hr {{
  border: none;
  border-top: 0.5px solid var(--separator);
  margin: 24px 0;
}}

.reflection-content strong {{
  font-weight: 600;
  color: var(--text-primary);
}}

.reflection-content em {{
  font-style: italic;
  opacity: 0.85;
}}

/* === TAGS === */
.tags {{
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 14px;
}}

.tag {{
  font-size: 12px;
  font-weight: 500;
  color: var(--accent);
  background: var(--accent-soft);
  padding: 4px 10px;
  border-radius: 14px;
}}

/* === EMPTY STATE === */
.empty-state {{
  text-align: center;
  padding: 80px 20px;
  color: var(--text-tertiary);
  animation: fadeIn 0.5s var(--transition);
}}

.empty-state .icon {{
  font-size: 56px;
  margin-bottom: 16px;
  opacity: 0.4;
  filter: grayscale(0.3);
}}

.empty-state p {{
  font-size: 16px;
  font-weight: 500;
}}

.empty-state .hint {{
  font-size: 13px;
  margin-top: 6px;
  opacity: 0.6;
}}

/* === DATE PICKER MODAL === */
.modal-overlay {{
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.5);
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  z-index: 300;
  opacity: 0;
  visibility: hidden;
  transition: var(--transition);
}}

.modal-overlay.active {{
  opacity: 1;
  visibility: visible;
}}

.modal {{
  position: fixed;
  inset: 0;
  display: flex;
  align-items: flex-end;
  justify-content: center;
  z-index: 301;
  pointer-events: none;
}}

.modal.active {{
  pointer-events: auto;
}}

.modal-sheet {{
  background: var(--bg-secondary);
  border-radius: var(--radius-lg) var(--radius-lg) 0 0;
  padding: 0 0 calc(20px + env(safe-area-inset-bottom, 0));
  width: 100%;
  max-width: 500px;
  max-height: 75vh;
  overflow-y: auto;
  transform: translateY(100%);
  transition: transform 0.4s cubic-bezier(0.32, 0.72, 0, 1);
  box-shadow: var(--shadow-xl);
}}

.modal.active .modal-sheet {{
  transform: translateY(0);
}}

.modal-handle {{
  width: 36px;
  height: 5px;
  background: var(--text-tertiary);
  border-radius: 3px;
  margin: 12px auto 8px;
  opacity: 0.3;
}}

.modal-title {{
  font-size: 17px;
  font-weight: 600;
  text-align: center;
  padding: 8px 20px 16px;
  color: var(--text-primary);
}}

/* Calendar */
.calendar-nav {{
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px 12px;
}}

.calendar-nav-btn {{
  width: 32px;
  height: 32px;
  border-radius: 50%;
  border: none;
  background: var(--bg-tertiary);
  color: var(--accent);
  font-size: 18px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: var(--transition-fast);
}}

.calendar-nav-btn:hover {{
  background: var(--accent-soft);
}}

.calendar-nav-btn:active {{
  transform: scale(0.9);
}}

.calendar-month {{
  font-size: 15px;
  font-weight: 600;
  color: var(--text-primary);
}}

.weekday-header {{
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  padding: 0 20px;
  margin-bottom: 4px;
}}

.weekday-header span {{
  text-align: center;
  font-size: 11px;
  font-weight: 600;
  color: var(--text-tertiary);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}}

.calendar-grid {{
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 4px;
  padding: 0 20px;
}}

.cal-cell {{
  aspect-ratio: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  font-size: 15px;
  font-weight: 500;
  cursor: pointer;
  transition: var(--transition-fast);
  position: relative;
  color: var(--text-primary);
  -webkit-tap-highlight-color: transparent;
}}

.cal-cell:hover {{
  background: var(--accent-soft);
}}

.cal-cell:active {{
  transform: scale(0.9);
}}

.cal-cell.other-month {{
  color: var(--text-tertiary);
  opacity: 0.4;
}}

.cal-cell.today {{
  font-weight: 700;
  color: var(--accent);
}}

.cal-cell.active {{
  background: var(--accent);
  color: white !important;
  font-weight: 700;
  box-shadow: 0 2px 8px rgba(0,122,255,0.3);
}}

.cal-cell.has-reflection::after {{
  content: '';
  position: absolute;
  bottom: 5px;
  width: 5px;
  height: 5px;
  border-radius: 50%;
  background: var(--accent);
  opacity: 0.7;
}}

.cal-cell.active.has-reflection::after {{
  background: white;
  opacity: 1;
}}

.cal-cell.empty {{
  pointer-events: none;
  visibility: hidden;
}}

.today-btn {{
  display: block;
  margin: 16px auto 0;
  padding: 10px 24px;
  border: none;
  border-radius: 20px;
  background: var(--accent-soft);
  color: var(--accent);
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  transition: var(--transition-fast);
}}

.today-btn:hover {{
  background: var(--accent);
  color: white;
}}

.today-btn:active {{
  transform: scale(0.96);
}}

/* === PROGRESS BAR === */
.progress-bar {{
  height: 3px;
  background: var(--bg-tertiary);
  border-radius: 2px;
  overflow: hidden;
  margin: 0 20px 24px;
}}

.progress-fill {{
  height: 100%;
  background: linear-gradient(90deg, var(--accent), #5ac8fa);
  border-radius: 2px;
  transition: width 0.5s var(--transition);
}}

/* === SCROLLBAR === */
::-webkit-scrollbar {{
  width: 0;
  height: 0;
}}

/* === RESPONSIVE === */
@media (max-width: 480px) {{
  .header-inner {{ padding: 10px 16px; }}
  .content {{ padding: calc(76px + env(safe-area-inset-top, 0)) 16px calc(80px + env(safe-area-inset-bottom, 0)); }}
  .date-hero .day-number {{ font-size: 56px; }}
  .reflection-content h1 {{ font-size: 19px; }}
  .reflection-content h2 {{ font-size: 16px; }}
  .card-body {{ padding: 16px 18px; }}
}}

/* === SWIPE HINT === */
.swipe-indicator {{
  display: flex;
  justify-content: center;
  gap: 6px;
  padding: 16px 0;
  opacity: 0;
  animation: fadeOut 3s 2s forwards;
}}

@keyframes fadeOut {{
  to {{ opacity: 0; visibility: hidden; }}
}}

.swipe-indicator span {{
  font-size: 12px;
  color: var(--text-tertiary);
}}

/* === SUMMARY CARD === */
.summary-card {{
  background: linear-gradient(135deg, var(--accent-soft), rgba(92,200,250,0.08));
  border: 0.5px solid rgba(0,122,255,0.15);
}}

@media (prefers-color-scheme: dark) {{
  .summary-card {{
    background: linear-gradient(135deg, var(--accent-soft), rgba(92,200,250,0.06));
  }}
}}

.summary-card .card-body {{
  font-size: 14px;
  line-height: 1.7;
  color: var(--text-primary);
}}

/* === STATS ROW === */
.stats-row {{
  display: flex;
  gap: 12px;
  margin-bottom: 16px;
}}

.stat-card {{
  flex: 1;
  background: var(--bg-secondary);
  border-radius: var(--radius);
  padding: 16px;
  text-align: center;
  box-shadow: var(--shadow-sm);
  animation: fadeInUp 0.4s var(--transition);
}}

.stat-value {{
  font-size: 24px;
  font-weight: 700;
  color: var(--accent);
  letter-spacing: -0.5px;
}}

.stat-label {{
  font-size: 11px;
  font-weight: 500;
  color: var(--text-tertiary);
  margin-top: 2px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}}
</style>
</head>
<body>

<!-- Header -->
<div class="header">
  <div class="header-inner">
    <button class="header-btn" id="prevBtn" title="前一天" aria-label="前一天">‹</button>
    <div class="header-center" id="headerCenter">
      <h1 id="headerTitle">每日反思</h1>
      <div class="subtitle" id="headerSubtitle">点击选择日期</div>
    </div>
    <button class="header-btn" id="nextBtn" title="后一天" aria-label="后一天">›</button>
  </div>
</div>

<!-- Main Content -->
<div class="content">
  <!-- Stats -->
  <div class="stats-row" id="statsRow">
    <div class="stat-card">
      <div class="stat-value" id="totalCount">--</div>
      <div class="stat-label">反思天数</div>
    </div>
    <div class="stat-card">
      <div class="stat-value" id="currentStreak">--</div>
      <div class="stat-label">当前连续</div>
    </div>
    <div class="stat-card">
      <div class="stat-value" id="currentIndex">--</div>
      <div class="stat-label">当前序号</div>
    </div>
  </div>

  <!-- Date Hero -->
  <div class="date-hero" id="dateHero">
    <div class="day-number" id="dayNumber">--</div>
    <div class="date-info">
      <span class="month-year" id="monthYear">----年--月</span>
      <span class="weekday" id="weekdayBadge">---</span>
    </div>
  </div>

  <!-- Summary Card (when reflection exists) -->
  <div class="card summary-card" id="summaryCard" style="display:none;">
    <div class="card-body">
      <p id="summaryText"></p>
      <div class="tags" id="tagsRow"></div>
    </div>
  </div>

  <!-- Reflection Card -->
  <div class="card" id="reflectionCard" style="display:none;">
    <div class="card-header">
      <h2>📝 反思内容</h2>
      <span class="badge" id="progressBadge"></span>
    </div>
    <div class="card-body reflection-content" id="cardContent"></div>
  </div>

  <!-- Empty State -->
  <div class="empty-state" id="emptyState">
    <div class="icon">�</div>
    <p>选择日期查看反思</p>
    <p class="hint">点击顶部日期打开日历</p>
  </div>
</div>

<!-- Date Picker Modal -->
<div class="modal-overlay" id="modalOverlay"></div>
<div class="modal" id="modal">
  <div class="modal-sheet" id="modalSheet">
    <div class="modal-handle"></div>
    <div class="modal-title">选择日期</div>
    <div class="calendar-nav">
      <button class="calendar-nav-btn" id="calPrevMonth">‹</button>
      <span class="calendar-month" id="calMonthLabel"></span>
      <button class="calendar-nav-btn" id="calNextMonth">›</button>
    </div>
    <div class="weekday-header">
      <span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span>
    </div>
    <div class="calendar-grid" id="calendarGrid"></div>
    <button class="today-btn" id="todayBtn">回到今天</button>
  </div>
</div>

<script>
const reflections = {data_json};

const dateMap = new Map();
reflections.forEach(r => dateMap.set(r.date, r));

const weekdays = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];
const monthNames = ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'];

let currentDate = reflections.length > 0 ? reflections[reflections.length - 1].date : null;
let calendarYear = 2026;
let calendarMonth = 7;

// Touch handling for swipe
let touchStartX = 0;
let touchStartY = 0;
let touchEndX = 0;
let touchEndY = 0;

function formatDate(dateStr) {{
  const [y, m, d] = dateStr.split('-').map(Number);
  return {{ year: y, month: m, day: d }};
}}

function getDateString(year, month, day) {{
  return `${{year}}-${{String(month).padStart(2,'0')}}-${{String(day).padStart(2,'0')}}`;
}}

function updateDisplay() {{
  if (!currentDate) return;
  const {{ year, month, day }} = formatDate(currentDate);
  const date = new Date(year, month - 1, day);
  
  // Update header
  document.getElementById('headerTitle').textContent = `${{year}}.${{String(month).padStart(2,'0')}}.${{String(day).padStart(2,'0')}}`;
  document.getElementById('headerSubtitle').textContent = weekdays[date.getDay()];
  
  // Update date hero
  document.getElementById('dayNumber').textContent = day;
  document.getElementById('monthYear').textContent = `${{year}}年${{monthNames[month-1]}}`;
  document.getElementById('weekdayBadge').textContent = weekdays[date.getDay()];
  
  // Update stats
  const totalReflections = reflections.length;
  const currentIdx = reflections.findIndex(r => r.date === currentDate);
  document.getElementById('totalCount').textContent = totalReflections;
  document.getElementById('currentIndex').textContent = currentIdx >= 0 ? `#${{currentIdx + 1}}` : '--';
  
  // Calculate streak
  let streak = 0;
  for (let i = reflections.length - 1; i >= 0; i--) {{
    const d = new Date(reflections[i].date);
    const expected = new Date();
    expected.setDate(expected.getDate() - (reflections.length - 1 - i));
    if (d.toDateString() === expected.toDateString() || i === reflections.length - 1) {{
      streak++;
    }} else {{
      break;
    }}
  }}
  document.getElementById('currentStreak').textContent = streak;
  
  // Update reflection content
  const reflection = dateMap.get(currentDate);
  const card = document.getElementById('reflectionCard');
  const summaryCard = document.getElementById('summaryCard');
  const emptyState = document.getElementById('emptyState');
  
  if (reflection) {{
    card.style.display = 'block';
    summaryCard.style.display = 'block';
    emptyState.style.display = 'none';
    
    // Summary
    document.getElementById('summaryText').textContent = reflection.summary || '暂无摘要';
    
    // Tags
    const tagsRow = document.getElementById('tagsRow');
    tagsRow.innerHTML = '';
    if (reflection.tags && reflection.tags.length > 0) {{
      reflection.tags.forEach(tag => {{
        const span = document.createElement('span');
        span.className = 'tag';
        span.textContent = tag;
        tagsRow.appendChild(span);
      }});
    }}
    
    // Content
    document.getElementById('cardContent').innerHTML = renderMarkdown(reflection.content);
    
    // Progress badge
    const progress = currentIdx >= 0 ? Math.round(((currentIdx + 1) / totalReflections) * 100) : 0;
    document.getElementById('progressBadge').textContent = `${{progress}}%`;
    
  }} else {{
    card.style.display = 'none';
    summaryCard.style.display = 'none';
    emptyState.style.display = 'block';
  }}
  
  // Update nav buttons
  document.getElementById('prevBtn').disabled = currentIdx <= 0;
  document.getElementById('nextBtn').disabled = currentIdx >= reflections.length - 1;
  
  // Update calendar if open
  if (document.getElementById('modal').classList.contains('active')) {{
    renderCalendar();
  }}
}}

function renderMarkdown(md) {{
  let html = md;
  
  // Code blocks
  html = html.replace(/```(\\w+)?\\n([\\s\\S]*?)```/g, '<pre><code>$2</code></pre>');
  
  // Inline code
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');
  
  // Headers
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');
  
  // Tables
  html = html.replace(/^\\|(.+)\\|$/gm, function(match) {{
    const cells = match.split('|').filter(c => c.trim() && !/^[-:]+$/.test(c.trim()));
    if (cells.length === 0) return '';
    return '<tr>' + cells.map(c => `<td>${{c.trim()}}</td>`).join('') + '</tr>';
  }});
  html = html.replace(/((<tr>.*</tr>\\n?)+)/g, '<table>$1</table>');
  
  // Blockquotes
  html = html.replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>');
  
  // Horizontal rules
  html = html.replace(/^---$/gm, '<hr>');
  
  // Bold
  html = html.replace(/\\*\\*(.+?)\\*\\*/g, '<strong>$1</strong>');
  
  // Italic
  html = html.replace(/\\*(.+?)\\*/g, '<em>$1</em>');
  
  // Unordered lists
  html = html.replace(/^- (.+)$/gm, '<li>$1</li>');
  html = html.replace(/((<li>.*</li>\\n?)+)/g, '<ul>$1</ul>');
  
  // Numbered lists
  html = html.replace(/^\\d+\\. (.+)$/gm, '<li>$1</li>');
  
  // Paragraphs
  html = html.replace(/\\n\\n/g, '</p><p>');
  html = '<p>' + html + '</p>';
  
  // Clean up
  html = html.replace(/<p>(<h[1-6]|<blockquote|<table|<ul|<pre|<hr)/g, '$1');
  html = html.replace(/(<\\/h[1-6]>|<\\/blockquote>|<\\/table>|<\\/ul>|<\\/pre>|<hr>)<p>/g, '$1');
  html = html.replace(/<p><\\/p>/g, '');
  html = html.replace(/<li>/g, '<li style="list-style:disc">');
  
  return html;
}}

function openModal() {{
  const overlay = document.getElementById('modalOverlay');
  const modal = document.getElementById('modal');
  overlay.classList.add('active');
  modal.classList.add('active');
  
  // Set calendar to current date's month
  if (currentDate) {{
    const {{ year, month }} = formatDate(currentDate);
    calendarYear = year;
    calendarMonth = month;
  }}
  renderCalendar();
}}

function closeModal() {{
  document.getElementById('modalOverlay').classList.remove('active');
  document.getElementById('modal').classList.remove('active');
}}

function renderCalendar() {{
  const grid = document.getElementById('calendarGrid');
  const label = document.getElementById('calMonthLabel');
  
  label.textContent = `${{calendarYear}}年${{monthNames[calendarMonth-1]}}`;
  grid.innerHTML = '';
  
  const today = new Date();
  const todayStr = getDateString(today.getFullYear(), today.getMonth() + 1, today.getDate());
  
  const daysInMonth = new Date(calendarYear, calendarMonth, 0).getDate();
  const firstDay = new Date(calendarYear, calendarMonth - 1, 1).getDay();
  const prevMonthDays = new Date(calendarYear, calendarMonth - 1, 0).getDate();
  
  // Previous month days
  for (let i = firstDay - 1; i >= 0; i--) {{
    const cell = document.createElement('div');
    cell.className = 'cal-cell other-month';
    cell.textContent = prevMonthDays - i;
    grid.appendChild(cell);
  }}
  
  // Current month days
  for (let day = 1; day <= daysInMonth; day++) {{
    const dateStr = getDateString(calendarYear, calendarMonth, day);
    const cell = document.createElement('div');
    cell.className = 'cal-cell';
    
    if (dateMap.has(dateStr)) cell.classList.add('has-reflection');
    if (dateStr === todayStr) cell.classList.add('today');
    if (dateStr === currentDate) cell.classList.add('active');
    
    cell.textContent = day;
    cell.onclick = () => {{
      currentDate = dateStr;
      updateDisplay();
      closeModal();
    }};
    
    grid.appendChild(cell);
  }}
  
  // Next month days
  const totalCells = firstDay + daysInMonth;
  const remaining = totalCells % 7 === 0 ? 0 : 7 - (totalCells % 7);
  for (let i = 1; i <= remaining; i++) {{
    const cell = document.createElement('div');
    cell.className = 'cal-cell other-month';
    cell.textContent = i;
    grid.appendChild(cell);
  }}
}}

function goToToday() {{
  const today = new Date();
  const todayStr = getDateString(today.getFullYear(), today.getMonth() + 1, today.getDate());
  
  // Find nearest reflection date
  if (dateMap.has(todayStr)) {{
    currentDate = todayStr;
  }} else {{
    // Find closest past date
    for (let i = reflections.length - 1; i >= 0; i--) {{
      if (reflections[i].date <= todayStr) {{
        currentDate = reflections[i].date;
        break;
      }}
    }}
  }}
  
  updateDisplay();
  closeModal();
}}

// Event listeners
document.getElementById('headerCenter').addEventListener('click', openModal);
document.getElementById('modalOverlay').addEventListener('click', closeModal);

document.getElementById('prevBtn').addEventListener('click', () => {{
  const idx = reflections.findIndex(r => r.date === currentDate);
  if (idx > 0) {{
    currentDate = reflections[idx - 1].date;
    updateDisplay();
  }}
}});

document.getElementById('nextBtn').addEventListener('click', () => {{
  const idx = reflections.findIndex(r => r.date === currentDate);
  if (idx < reflections.length - 1) {{
    currentDate = reflections[idx + 1].date;
    updateDisplay();
  }}
}});

document.getElementById('calPrevMonth').addEventListener('click', () => {{
  calendarMonth--;
  if (calendarMonth < 1) {{ calendarMonth = 12; calendarYear--; }}
  renderCalendar();
}});

document.getElementById('calNextMonth').addEventListener('click', () => {{
  calendarMonth++;
  if (calendarMonth > 12) {{ calendarMonth = 1; calendarYear++; }}
  renderCalendar();
}});

document.getElementById('todayBtn').addEventListener('click', goToToday);

// Keyboard navigation
document.addEventListener('keydown', (e) => {{
  if (document.getElementById('modal').classList.contains('active')) return;
  if (e.key === 'ArrowLeft') {{
    document.getElementById('prevBtn').click();
  }} else if (e.key === 'ArrowRight') {{
    document.getElementById('nextBtn').click();
  }}
}});

// Touch/swipe navigation
document.addEventListener('touchstart', (e) => {{
  touchStartX = e.changedTouches[0].screenX;
  touchStartY = e.changedTouches[0].screenY;
}}, {{ passive: true }});

document.addEventListener('touchend', (e) => {{
  touchEndX = e.changedTouches[0].screenX;
  touchEndY = e.changedTouches[0].screenY;
  handleSwipe();
}}, {{ passive: true }});

function handleSwipe() {{
  const diffX = touchStartX - touchEndX;
  const diffY = touchStartY - touchEndY;
  
  if (Math.abs(diffX) > Math.abs(diffY) && Math.abs(diffX) > 60) {{
    if (diffX > 0) {{
      // Swipe left -> next
      document.getElementById('nextBtn').click();
    }} else {{
      // Swipe right -> prev
      document.getElementById('prevBtn').click();
    }}
  }}
}}

// Initialize
updateDisplay();
</script>
</body>
</html>'''
    
    # Write HTML file
    output_path = workspace / 'reflections.html'
    output_path.write_text(html, encoding='utf-8')
    print(f"Generated {output_path}")
    print(f"Total reflections: {len(reflections)}")
    for r in reflections:
        fname = r.get('filename', f"{r['date']}-merged")
        print(f"  {r['date']}: {fname}")

if __name__ == '__main__':
    main()
